src/main/java/com/ceos/beatbuddy/domain/member/entity/Member.java, src/main/java/com/ceos/beatbuddy/domain/member/entity/MemberGenre.java, src/main/java/com/ceos/beatbuddy/domain/member/entity/MemberMood.java
- Closes #3
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> ✨ [FEAT] 멤버와 연관관계 데이터 삭제되도록 로직 추가

src/main/java/com/ceos/beatbuddy/global/config/oauth/CustomClientRegistrationRepo.java, src/main/java/com/ceos/beatbuddy/global/config/oauth/CustomOAuth2UserService.java, src/main/java/com/ceos/beatbuddy/global/config/oauth/dto/GoogleResponse.java
- Closes #16
어떤 변경 사항이 있나요?
1. 작업 내용
-
=>  [Feat/#16] 구글 로그인 연동 완료

src/main/java/com/ceos/beatbuddy/domain/magazine/controller/MagazineApiDocs.java, src/main/java/com/ceos/beatbuddy/domain/magazine/controller/MagazineController.java
- Closes #15
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> [Docs/#15] 매거진 작성 스웨거 수정

src/main/java/com/ceos/beatbuddy/domain/archive/exception/ArchiveErrorCode.java, src/main/java/com/ceos/beatbuddy/domain/comment/exception/CommentErrorCode.java, src/main/java/com/ceos/beatbuddy/domain/heartbeat/exception/HeartbeatErrorCode.java, src/main/java/com/ceos/beatbuddy/domain/magazine/application/MagazineService.java, src/main/java/com/ceos/beatbuddy/domain/magazine/controller/MagazineApiDocs.java, src/main/java/com/ceos/beatbuddy/domain/magazine/controller/MagazineController.java, src/main/java/com/ceos/beatbuddy/domain/magazine/dto/MagazineDetailDTO.java, src/main/java/com/ceos/beatbuddy/domain/magazine/dto/MagazineHomeResponseDTO.java, src/main/java/com/ceos/beatbuddy/domain/magazine/dto/MagazineRequestDTO.java, src/main/java/com/ceos/beatbuddy/domain/magazine/entity/Magazine.java, src/main/java/com/ceos/beatbuddy/domain/magazine/exception/MagazineErrorCode.java, src/main/java/com/ceos/beatbuddy/domain/magazine/repository/MagazineRepository.java, src/main/java/com/ceos/beatbuddy/domain/member/exception/MemberErrorCode.java, src/main/java/com/ceos/beatbuddy/domain/member/exception/MemberGenreErrorCode.java, src/main/java/com/ceos/beatbuddy/domain/member/exception/MemberMoodErrorCode.java, src/main/java/com/ceos/beatbuddy/domain/post/application/PostService.java, src/main/java/com/ceos/beatbuddy/domain/post/controller/PostController.java, src/main/java/com/ceos/beatbuddy/domain/post/exception/PostErrorCode.java, src/main/java/com/ceos/beatbuddy/domain/search/exception/SearchErrorCode.java, src/main/java/com/ceos/beatbuddy/domain/vector/exception/VectorErrorCode.java, src/main/java/com/ceos/beatbuddy/domain/venue/exception/VenueErrorCode.java, src/main/java/com/ceos/beatbuddy/domain/venue/exception/VenueGenreErrorCode.java, src/main/java/com/ceos/beatbuddy/domain/venue/exception/VenueMoodErrorCode.java, src/main/java/com/ceos/beatbuddy/global/ApiCode.java, src/main/java/com/ceos/beatbuddy/global/CustomException.java, src/main/java/com/ceos/beatbuddy/global/GlobalExceptionHandler.java, src/main/java/com/ceos/beatbuddy/global/ResponseException.java, src/main/java/com/ceos/beatbuddy/global/code/SuccessCode.java, src/main/java/com/ceos/beatbuddy/global/config/oauth/exception/OauthErrorCode.java, src/main/java/com/ceos/beatbuddy/global/dto/ErrorResponseDTO.java
- Closes #20
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> [Feat/#20] magazine read and status

src/main/java/com/ceos/beatbuddy/domain/magazine/application/MagazineService.java, src/main/java/com/ceos/beatbuddy/domain/scrap/repository/MagazineScrapRepository.java
- Closes #25
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> [Refactor/#25] 메소드 이름 findAllBy로 변경

src/main/java/com/ceos/beatbuddy/domain/magazine/application/MagazineService.java, src/main/java/com/ceos/beatbuddy/domain/magazine/controller/MagazineApiDocs.java, src/main/java/com/ceos/beatbuddy/domain/magazine/controller/MagazineController.java, src/main/java/com/ceos/beatbuddy/domain/magazine/dto/MagazineDetailDTO.java, src/main/java/com/ceos/beatbuddy/domain/magazine/dto/MagazineHomeResponseDTO.java, src/main/java/com/ceos/beatbuddy/domain/magazine/entity/Magazine.java, src/main/java/com/ceos/beatbuddy/domain/post/entity/Post.java, src/main/java/com/ceos/beatbuddy/domain/scrapandlike/entity/AbstractScrap.java, src/main/java/com/ceos/beatbuddy/domain/scrapandlike/entity/MagazineLike.java, src/main/java/com/ceos/beatbuddy/domain/scrapandlike/entity/MagazineScrap.java, src/main/java/com/ceos/beatbuddy/domain/scrapandlike/entity/PostLike.java, src/main/java/com/ceos/beatbuddy/domain/scrapandlike/entity/PostScrap.java, src/main/java/com/ceos/beatbuddy/domain/scrapandlike/repository/MagazineLikeRepository.java, src/main/java/com/ceos/beatbuddy/domain/scrapandlike/repository/MagazineScrapRepository.java, src/main/java/com/ceos/beatbuddy/global/code/SuccessCode.java
- Closes #28
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> [Feat/#28] magazine like

src/main/java/com/ceos/beatbuddy/domain/magazine/application/MagazineService.java, src/main/java/com/ceos/beatbuddy/domain/magazine/controller/MagazineApiDocs.java, src/main/java/com/ceos/beatbuddy/domain/magazine/exception/MagazineErrorCode.java, src/main/java/com/ceos/beatbuddy/domain/scrapandlike/repository/MagazineLikeRepository.java
- Closes #28
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> [Feat/#28] magazine like, 중복 좋아요 예외처리

src/main/java/com/ceos/beatbuddy/domain/magazine/application/MagazineService.java, src/main/java/com/ceos/beatbuddy/domain/magazine/controller/MagazineApiDocs.java, src/main/java/com/ceos/beatbuddy/domain/magazine/controller/MagazineController.java, src/main/java/com/ceos/beatbuddy/domain/magazine/exception/MagazineErrorCode.java, src/main/java/com/ceos/beatbuddy/global/code/SuccessCode.java
- Closes #30
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> [Feat/#30] 좋아요 취소 예외 및 로직 처리 구현

src/main/java/com/ceos/beatbuddy/domain/magazine/application/MagazineService.java, src/main/java/com/ceos/beatbuddy/domain/magazine/controller/MagazineApiDocs.java, src/main/java/com/ceos/beatbuddy/domain/magazine/controller/MagazineController.java, src/main/java/com/ceos/beatbuddy/domain/magazine/exception/MagazineErrorCode.java, src/main/java/com/ceos/beatbuddy/global/CustomException.java, src/main/java/com/ceos/beatbuddy/global/code/ErrorCode.java, src/main/java/com/ceos/beatbuddy/global/code/SuccessCode.java
- Closes #37
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> [Feat/#37] 스크랩 삭제 구현

src/main/java/com/ceos/beatbuddy/domain/magazine/controller/MagazineApiDocs.java
- Closes #37
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> [Docs/#37] 스웨거 설명 수정

src/main/java/com/ceos/beatbuddy/domain/event/application/EventService.java, src/main/java/com/ceos/beatbuddy/domain/event/controller/EventApiDocs.java, src/main/java/com/ceos/beatbuddy/domain/event/controller/EventController.java, src/main/java/com/ceos/beatbuddy/domain/event/dto/EventCreateRequestDTO.java, src/main/java/com/ceos/beatbuddy/domain/event/dto/EventResponseDTO.java, src/main/java/com/ceos/beatbuddy/domain/event/entity/Event.java, src/main/java/com/ceos/beatbuddy/domain/event/repository/EventRepository.java, src/main/java/com/ceos/beatbuddy/domain/magazine/controller/MagazineApiDocs.java, src/main/java/com/ceos/beatbuddy/domain/magazine/dto/MagazineRequestDTO.java, src/main/java/com/ceos/beatbuddy/domain/scrapandlike/repository/MagazineLikeRepository.java, src/main/java/com/ceos/beatbuddy/domain/scrapandlike/repository/MagazineScrapRepository.java, src/main/java/com/ceos/beatbuddy/global/code/SuccessCode.java
- Closes #45
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> [Feat/#45] create event

src/main/java/com/ceos/beatbuddy/domain/event/controller/EventApiDocs.java, src/main/java/com/ceos/beatbuddy/domain/event/dto/EventCreateRequestDTO.java, src/main/java/com/ceos/beatbuddy/domain/event/dto/EventResponseDTO.java, src/main/java/com/ceos/beatbuddy/domain/event/entity/Event.java
- Closes #45
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> [feat/#45] 이벤트 참석 정보 수집 여부 필드 추가

src/main/java/com/ceos/beatbuddy/domain/vector/dto/MoodRequestDTO.java
- Closes #55
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> [Feat/#55] mood에 BAR&CAFE 추가

src/main/java/com/ceos/beatbuddy/domain/event/application/EventService.java, src/main/java/com/ceos/beatbuddy/domain/event/controller/EventApiDocs.java, src/main/java/com/ceos/beatbuddy/domain/event/controller/EventController.java, src/main/java/com/ceos/beatbuddy/domain/event/exception/EventErrorCode.java, src/main/java/com/ceos/beatbuddy/domain/event/repository/EventScrapRepository.java, src/main/java/com/ceos/beatbuddy/global/code/SuccessCode.java
- Closes #58
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> [Feat/#58] event scrap 추가 및 삭제 구현 완료

src/main/java/com/ceos/beatbuddy/domain/event/repository/EventAttendanceRepository.java, src/main/java/com/ceos/beatbuddy/domain/event/repository/EventLikeRepository.java, src/main/java/com/ceos/beatbuddy/domain/event/repository/EventRepository.java, src/main/java/com/ceos/beatbuddy/domain/mypage/application/MyPageService.java, src/main/java/com/ceos/beatbuddy/domain/mypage/controller/MyPageApiDocs.java, src/main/java/com/ceos/beatbuddy/domain/mypage/controller/MyPageController.java, src/main/java/com/ceos/beatbuddy/global/code/SuccessCode.java
- Closes #70
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> [Feat/#70] 마이페이지 이벤트 조회

src/main/java/com/ceos/beatbuddy/domain/follow/application/FollowService.java, src/main/java/com/ceos/beatbuddy/domain/follow/controller/FollowApiDocs.java, src/main/java/com/ceos/beatbuddy/domain/follow/controller/FollowController.java, src/main/java/com/ceos/beatbuddy/domain/follow/dto/FollowResponseDTO.java, src/main/java/com/ceos/beatbuddy/domain/follow/entity/Follow.java, src/main/java/com/ceos/beatbuddy/domain/follow/entity/FollowId.java, src/main/java/com/ceos/beatbuddy/domain/follow/exception/FollowErrorCode.java, src/main/java/com/ceos/beatbuddy/domain/follow/repository/FollowRepository.java, src/main/java/com/ceos/beatbuddy/domain/member/entity/Member.java, src/main/java/com/ceos/beatbuddy/global/code/SuccessCode.java
- Closes #72
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> [Feat/#72] 팔로우, 언팔로우, 내가 팔로잉한 목록, 내가 팔로잉된 목록 조회

src/main/java/com/ceos/beatbuddy/domain/event/application/EventService.java, src/main/java/com/ceos/beatbuddy/domain/event/controller/EventApiDocs.java, src/main/java/com/ceos/beatbuddy/domain/event/controller/EventController.java, src/main/java/com/ceos/beatbuddy/domain/magazine/application/MagazineService.java, src/main/java/com/ceos/beatbuddy/domain/member/application/MemberService.java, src/main/java/com/ceos/beatbuddy/domain/member/controller/MemberController.java, src/main/java/com/ceos/beatbuddy/domain/member/entity/Member.java, src/main/java/com/ceos/beatbuddy/domain/post/application/PostService.java, src/main/java/com/ceos/beatbuddy/domain/venue/application/VenueInfoService.java, src/main/java/com/ceos/beatbuddy/global/UploadUtil.java, src/main/java/com/ceos/beatbuddy/global/code/SuccessCode.java
- Closes #74
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> [Feat/#74] member profile image upload

src/main/java/com/ceos/beatbuddy/domain/member/controller/MemberController.java, src/main/java/com/ceos/beatbuddy/domain/post/controller/PostController.java, src/main/java/com/ceos/beatbuddy/domain/post/dto/ResponsePostDto.java
- Closes #77
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> [Feat/#77] post 조회시 role 전달

src/main/java/com/ceos/beatbuddy/domain/post/application/PostService.java, src/main/java/com/ceos/beatbuddy/domain/post/controller/PostApiDocs.java, src/main/java/com/ceos/beatbuddy/domain/post/controller/PostController.java, src/main/java/com/ceos/beatbuddy/domain/post/dto/PostCreateRequestDTO.java, src/main/java/com/ceos/beatbuddy/domain/post/entity/FreePost.java, src/main/java/com/ceos/beatbuddy/domain/post/entity/Post.java, src/main/java/com/ceos/beatbuddy/domain/post/repository/FreePostRepository.java, src/main/java/com/ceos/beatbuddy/domain/post/repository/PiecePostRepository.java, src/main/java/com/ceos/beatbuddy/global/code/SuccessCode.java
내부에 글 작성하는 swagger 에 이상으로 해당 부분도 수정
- Closes #84
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> [Feat/#84] 내가 작성한 글 불러오기 구현

src/main/java/com/ceos/beatbuddy/domain/comment/entity/Comment.java, src/main/java/com/ceos/beatbuddy/domain/comment/repository/CommentRepository.java, src/main/java/com/ceos/beatbuddy/domain/post/application/PostService.java, src/main/java/com/ceos/beatbuddy/domain/post/controller/PostApiDocs.java, src/main/java/com/ceos/beatbuddy/domain/post/controller/PostController.java, src/main/java/com/ceos/beatbuddy/domain/post/dto/PostPageResponseDTO.java, src/main/java/com/ceos/beatbuddy/domain/post/repository/FreePostRepository.java, src/main/java/com/ceos/beatbuddy/domain/scrapandlike/entity/PostLike.java, src/main/java/com/ceos/beatbuddy/domain/scrapandlike/entity/PostScrap.java, src/main/java/com/ceos/beatbuddy/domain/scrapandlike/repository/PostLikeRepository.java, src/main/java/com/ceos/beatbuddy/domain/scrapandlike/repository/PostScrapRepository.java, src/main/java/com/ceos/beatbuddy/global/code/SuccessCode.java
- Closes #87
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> [Refactor/#87] 부하테스트 이후 게시글 조회 관련 api 정리

src/main/java/com/ceos/beatbuddy/domain/member/application/BusinessMemberService.java, src/main/java/com/ceos/beatbuddy/domain/member/application/OnboardingService.java, src/main/java/com/ceos/beatbuddy/domain/member/controller/BusinessMemberController.java
- Closes #109
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> [Refactor/#109] 닉네임 유효성 검사 로직 가독성 개선

src/main/java/com/ceos/beatbuddy/global/config/oauth/OAuth2SuccessHandler.java
- Closes #164
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> [Feat/#164] sub 고유번호를 통해 loginid 저장

src/main/java/com/ceos/beatbuddy/domain/member/application/OnboardingService.java, src/main/java/com/ceos/beatbuddy/domain/member/entity/Member.java
- Closes #207
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> [Fix/#207] version 초기화

src/main/java/com/ceos/beatbuddy/domain/comment/application/CommentService.java, src/main/java/com/ceos/beatbuddy/domain/comment/repository/CommentRepository.java
- Closes #226
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> [Fix/#226] 레포지토리 메소드 이름 변경

src/main/java/com/ceos/beatbuddy/domain/member/controller/MemberApiDocs.java, src/main/java/com/ceos/beatbuddy/domain/member/controller/MemberController.java, src/main/java/com/ceos/beatbuddy/domain/member/repository/MemberQueryRepositoryImpl.java
- Closes #276
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> [Feat/#276] 사용자 프로필 요약 memberId 로 진행

src/main/java/com/ceos/beatbuddy/domain/admin/application/AdminService.java, src/main/java/com/ceos/beatbuddy/domain/admin/controller/AdminController.java, src/main/java/com/ceos/beatbuddy/domain/member/application/BusinessMemberService.java, src/main/java/com/ceos/beatbuddy/domain/member/entity/BusinessInfo.java, src/main/java/com/ceos/beatbuddy/domain/member/exception/MemberErrorCode.java, src/main/java/com/ceos/beatbuddy/global/code/SuccessCode.java
- Closes #286
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> [Feat/#286] 비즈니스 멤버 승인 처리 구현

src/main/java/com/ceos/beatbuddy/domain/member/application/MemberService.java, src/main/java/com/ceos/beatbuddy/domain/member/controller/MemberApiDocs.java, src/main/java/com/ceos/beatbuddy/domain/member/controller/MemberController.java
- Closes #290
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> [Feat/#290] 프로필 조회 memberId Optional

src/main/java/com/ceos/beatbuddy/domain/member/controller/MemberApiDocs.java, src/main/java/com/ceos/beatbuddy/domain/member/controller/MemberController.java
- Closes #290
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> [Feat/#290]  PathVariable -> RequestParam 으로 변경

src/main/java/com/ceos/beatbuddy/domain/comment/application/CommentService.java, src/main/java/com/ceos/beatbuddy/domain/comment/entity/Comment.java, src/main/java/com/ceos/beatbuddy/domain/comment/presentation/CommentController.java, src/main/java/com/ceos/beatbuddy/domain/comment/repository/CommentRepository.java, src/main/java/com/ceos/beatbuddy/domain/scrapandlike/entity/CommentLike.java, src/main/java/com/ceos/beatbuddy/domain/scrapandlike/repository/CommentLikeRepository.java
- Closes #296
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> [Feat/#296] 댓글 좋아요 및 삭제 구현 완료

src/main/java/com/ceos/beatbuddy/domain/search/controller/SearchController.java, src/main/java/com/ceos/beatbuddy/domain/search/dto/SearchDropDownDTO.java, src/main/java/com/ceos/beatbuddy/domain/venue/repository/VenueRepository.java
- Closes #
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> 📝 [DOCS] 요청 상세 설명 작성

src/main/java/com/ceos/beatbuddy/domain/comment/application/CommentService.java, src/main/java/com/ceos/beatbuddy/domain/scrapandlike/repository/CommentLikeRepository.java
- Closes #303
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> [Fix/#303] 댓글 삭제 시 좋아요 연관 데이터 버그 해결

src/main/java/com/ceos/beatbuddy/domain/firebase/api/FirebaseListResponseApi.java, src/main/java/com/ceos/beatbuddy/domain/firebase/controller/FirebaseMessageApiDocs.java, src/main/java/com/ceos/beatbuddy/domain/firebase/dto/NotificationListDTO.java, src/main/java/com/ceos/beatbuddy/domain/firebase/dto/NotificationPageDTO.java, src/main/java/com/ceos/beatbuddy/global/dto/ResponseDTO.java
- Closes #307
어떤 변경 사항이 있나요?
1. 작업 내용
- Add FirebaseListResponseApi for structured list responses
- Update NotificationListDTO to include notification IDs
- Enhance NotificationPageDTO with pagination metadata
- Modify ResponseDTO to support generic list responses
- Update API documentation with new response format
=> [Feat/#307] Add notification list API with ID filtering support

src/main/java/com/ceos/beatbuddy/domain/post/dto/PostPageResponseDTO.java, src/main/java/com/ceos/beatbuddy/domain/post/entity/FreePost.java, src/main/java/com/ceos/beatbuddy/domain/search/application/SearchService.java, src/main/java/com/ceos/beatbuddy/domain/search/controller/SearchController.java, src/main/java/com/ceos/beatbuddy/domain/search/dto/SearchDropDownDTO.java, src/main/java/com/ceos/beatbuddy/domain/search/dto/SearchPageResponseDTO.java, src/main/java/com/ceos/beatbuddy/domain/search/dto/SearchQueryResponseDTO.java, src/main/java/com/ceos/beatbuddy/domain/search/exception/SearchErrorCode.java, src/main/java/com/ceos/beatbuddy/domain/venue/application/VenueSearchService.java
- Closes #
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> [Fix/#309] drop down pagination

src/main/java/com/ceos/beatbuddy/domain/comment/application/CommentService.java
- Closes #315
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> [Fix/#315] 대댓글이 있는 댓글 삭제 시 isDeleted 플래그를 true 로 전달하도록

src/main/java/com/ceos/beatbuddy/domain/member/application/MemberService.java, src/main/java/com/ceos/beatbuddy/domain/member/controller/MemberController.java, src/main/java/com/ceos/beatbuddy/domain/member/dto/MemberProfileSummaryDTO.java, src/main/java/com/ceos/beatbuddy/domain/member/repository/MemberQueryRepositoryImpl.java, src/main/java/com/ceos/beatbuddy/global/code/SuccessCode.java
- Closes #331
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> [Feat/#331] get post profile

event.json, src/main/java/com/ceos/beatbuddy/domain/event/application/EventElasticService.java
- Closes #346
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> [Feat/#346] 이벤트 검색 시 제목, 위치, 베뉴에 가중치 추가

src/main/java/com/ceos/beatbuddy/domain/event/application/EventElasticService.java
- Closes #346
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> feat: 제목, 위치, 베뉴 관련 이벤트 검색시 가중치 추가

src/main/java/com/ceos/beatbuddy/domain/search/application/SearchService.java, src/main/java/com/ceos/beatbuddy/domain/search/controller/SearchController.java
- Closes #359
어떤 변경 사항이 있나요?
1. 작업 내용
Sets "가까운 순" (nearest) as the default sorting criteria for map search functionality, while refactoring the SearchService to improve code maintainability and performance.
- Sets default value "가까운 순" for search criteria parameter in controller endpoints
- Refactors SearchService to use MemberService instead of direct repository access
- Optimizes Redis operations using pipeline for batch processing
- Extracts complex mapping logic into separate methods for better readability
=> [Feat/#359] map search default nearest

src/main/java/com/ceos/beatbuddy/domain/comment/repository/CommentRepository.java, src/main/java/com/ceos/beatbuddy/domain/post/application/PostInteractionService.java, src/main/java/com/ceos/beatbuddy/domain/post/application/PostService.java
- Closes #362
어떤 변경 사항이 있나요?
1. 작업 내용
This PR fixes a bug where deleted comments were still being counted when determining if a user has commented on a post. The fix ensures that only non-deleted comments are considered for user interaction tracking.
- Modified comment existence checks to exclude deleted comments
- Updated bulk comment queries to filter out deleted comments
- Added new repository methods with AndIsDeletedFalse suffix
=> [Fix/#362] post has commented

src/main/java/com/ceos/beatbuddy/domain/scrapandlike/repository/VenueReviewLikeRepository.java, src/main/java/com/ceos/beatbuddy/domain/venue/application/VenueReviewService.java, src/main/java/com/ceos/beatbuddy/domain/venue/controller/VenueReviewApiDocs.java, src/main/java/com/ceos/beatbuddy/domain/venue/dto/VenueReviewResponseDTO.java, src/main/java/com/ceos/beatbuddy/domain/venue/dto/api/VenueReviewListApi.java, src/main/java/com/ceos/beatbuddy/domain/venue/entity/VenueReview.java, src/main/java/com/ceos/beatbuddy/domain/venue/repository/VenueReviewQueryRepositoryImpl.java, src/main/java/com/ceos/beatbuddy/global/util/UploadUtilAsyncWrapper.java
- Closes #366
어떤 변경 사항이 있나요?
1. 작업 내용
This PR adds thumbnail image support for venue reviews. The implementation enables the system to generate and store both original images and their thumbnails when users upload images for venue reviews.
- Added thumbnail URL storage and retrieval functionality for venue reviews
- Extended the existing async upload wrapper to support review folder thumbnails
- Updated the image upload service integration to handle both original and thumbnail URLs
=> [Feat/#366] review media with thumbnails

src/main/java/com/ceos/beatbuddy/domain/venue/application/VenueInfoService.java, src/main/java/com/ceos/beatbuddy/domain/venue/dto/VenueInfoOptimizedData.java, src/main/java/com/ceos/beatbuddy/domain/venue/repository/VenueInfoQueryRepository.java, src/main/java/com/ceos/beatbuddy/domain/venue/repository/VenueInfoQueryRepositoryImpl.java, src/main/java/com/ceos/beatbuddy/domain/venue/repository/VenueReviewQueryRepositoryImpl.java
- Closes #372
어떤 변경 사항이 있나요?
1. 작업 내용
This PR fixes a QueryDSL issue where imageUrls.isNotEmpty() was incorrectly used on a non-collection field by replacing it with a null check using Expressions.booleanTemplate(). Additionally, it introduces query optimization for venue information retrieval by consolidating multiple database queries into a single optimized query.
- Replaces incorrect isNotEmpty() calls with proper null checks for the imageUrls field
- Adds new optimized query repository for venue information retrieval
- Refactors venue validation logic to use batch queries instead of individual lookups
=> [Fix/#372] querydsl imageurls noncollection

src/main/java/com/ceos/beatbuddy/global/GlobalExceptionHandler.java, src/main/java/com/ceos/beatbuddy/global/controller/TestController.java, src/main/java/com/ceos/beatbuddy/global/discord/CachingRequestFilter.java
- Closes #
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> [Fix/#382] 어드민 jwtFilter 순위 수정

src/main/java/com/ceos/beatbuddy/global/GlobalExceptionHandler.java, src/main/java/com/ceos/beatbuddy/global/config/oauth/OAuth2SuccessHandler.java, src/main/java/com/ceos/beatbuddy/global/discord/CachingRequestFilter.java
- Closes 
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> [Fix/#382] apple login redirect

src/main/java/com/ceos/beatbuddy/domain/member/entity/BusinessInfo.java, src/main/java/com/ceos/beatbuddy/global/discord/CachingRequestFilter.java
- Closes #
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> fix: ã: oauth 할 때ë는 캐시ê° filter 가 건들지 않도록

src/main/java/com/ceos/beatbuddy/domain/member/application/MemberService.java
- Closes #388
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> [Feat/#388] 팔로잉 한 사람 차단 시 팔로잉 관계 삭제

src/main/java/com/ceos/beatbuddy/domain/post/repository/PostQueryRepositoryImpl.java
- Closes #407
어떤 변경 사항이 있나요?
1. 작업 내용
- findPostsByHashtagsExcludingBlocked 메서드에서 해시태그 필터링 로직을 OR 조건으로 명확히 구현
- Stream과 reduce를 사용하여 각 해시태그에 대한 조건을 OR로 결합
- null 체크 로직 개선으로 안전성 향상
=> refactor: 해시태그 필터링을 명시적인 OR 조건으로 변경

src/main/java/com/ceos/beatbuddy/domain/member/application/OnboardingService.java, src/main/java/com/ceos/beatbuddy/domain/member/entity/Member.java, src/main/java/com/ceos/beatbuddy/domain/member/entity/PostProfileInfo.java, src/main/java/com/ceos/beatbuddy/domain/member/repository/MemberQueryRepositoryImpl.java, src/main/java/com/ceos/beatbuddy/domain/member/repository/MemberRepository.java
- Closes #411
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> [Feat/#411] profile summary businessname null fix

src/main/java/com/ceos/beatbuddy/domain/event/application/EventCommentService.java, src/main/java/com/ceos/beatbuddy/domain/event/application/EventService.java, src/main/java/com/ceos/beatbuddy/global/service/ImageUploadService.java
- Closes #422
어떤 변경 사항이 있나요?
1. 작업 내용
이 PR은 이미지 업로드 성능을 최적화하기 위해 병렬 처리 방식을 개선한 리팩토링입니다. 기존의 순차적 이미지 처리를 병렬 처리로 변경하여 응답 시간을 단축시키고자 합니다.
- 이미지 업로드를 위한 새로운 ImageUploadService 도입
- CompletableFuture.allOf()를 사용한 병렬 업로드 최적화
- EventService에서 병렬 이미지 업로드 방식 적용
=> [Refactor/#422] 이미지 병렬 요청으로 성능 최적화

src/main/java/com/ceos/beatbuddy/domain/firebase/repository/NotificationRepository.java
- Closes #421
어떤 변경 사항이 있나요?
1. 작업 내용
- NotificationRepository.findByReceiver()에 createdAt DESC 정렬 조건 추가
- 최근에 만들어진 알림이 목록 상단에 표시되도록 수정
=> [Fix/#421] firebase/notifications 알림 목록 최신 순으로 정렬

src/main/java/com/ceos/beatbuddy/domain/post/application/FreePostHandler.java, src/main/java/com/ceos/beatbuddy/domain/post/application/FreePostSearchService.java
- Closes #422
어떤 변경 사항이 있나요?
1. 작업 내용
- FreePostSearchService.save()와 delete() 메서드에 @Async 적용
- Elasticsearch 인덱싱이 Post 응답 시간에 영향을 주지 않도록 비동기 처리
=> perf: Post 생성 성능 최적화 - Elasticsearch 인덱싱 비동기 처리

src/main/java/com/ceos/beatbuddy/domain/search/application/SearchService.java, src/main/java/com/ceos/beatbuddy/domain/search/controller/SearchController.java, src/main/java/com/ceos/beatbuddy/domain/search/dto/SearchMapRequestDTO.java
- Closes #434
어떤 변경 사항이 있나요?
1. 작업 내용
- POST /search/map/search 엔드포인트 추가로 JSON body 요청 지원
- SearchMapRequestDTO 추가하여 좌표 정보 정확한 전달 가능
- SearchService에 거리순 정렬 시 좌표 null 체크 로직 강화
- haversine 메서드에 방어적 null 검증 추가
- "인기순" 요청 시 좌표 없이도 정상 작동, "가까운 순" 요청 시 좌표 필수 검증
=> [Fix/#434] 지도 베뉴 검색 JSON API 추가 및 좌표 검증 문제 해결

src/main/java/com/ceos/beatbuddy/domain/follow/entity/FollowCreatedEvent.java, src/main/java/com/ceos/beatbuddy/domain/follow/listener/FollowNotificationListener.java
- Closes #
어떤 변경 사항이 있나요?
1. 작업 내용
-
=> [Fix/#442] event response include
